name: Deploy Meteor.js App

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Meteor
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: ${{ runner.os }}-meteor-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-meteor-

      - name: Install Meteor
        run: |
          curl https://install.meteor.com/ | sh

      - name: Install Dependencies
        run: meteor npm install

      - name: Run Tests (optional)
        run: meteor npm test

      - name: Build Meteor App
        run: |
          meteor build --directory .output --server-only

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" .output/bundle/ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && pm2 restart meteor"

